/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutTableIndexImport } from './routes/_layout/table/index'
import { Route as LayoutChartIndexImport } from './routes/_layout/chart/index'
import { Route as LayoutTableTableIdImport } from './routes/_layout/table/$tableId'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTableIndexRoute = LayoutTableIndexImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutChartIndexRoute = LayoutChartIndexImport.update({
  id: '/chart/',
  path: '/chart/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTableTableIdRoute = LayoutTableTableIdImport.update({
  id: '/table/$tableId',
  path: '/table/$tableId',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/table/$tableId': {
      id: '/_layout/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/table/$tableId'
      preLoaderRoute: typeof LayoutTableTableIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/chart/': {
      id: '/_layout/chart/'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof LayoutChartIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/table/': {
      id: '/_layout/table/'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof LayoutTableIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutTableTableIdRoute: typeof LayoutTableTableIdRoute
  LayoutChartIndexRoute: typeof LayoutChartIndexRoute
  LayoutTableIndexRoute: typeof LayoutTableIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutTableTableIdRoute: LayoutTableTableIdRoute,
  LayoutChartIndexRoute: LayoutChartIndexRoute,
  LayoutTableIndexRoute: LayoutTableIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/table/$tableId': typeof LayoutTableTableIdRoute
  '/chart': typeof LayoutChartIndexRoute
  '/table': typeof LayoutTableIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/table/$tableId': typeof LayoutTableTableIdRoute
  '/chart': typeof LayoutChartIndexRoute
  '/table': typeof LayoutTableIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/table/$tableId': typeof LayoutTableTableIdRoute
  '/_layout/chart/': typeof LayoutChartIndexRoute
  '/_layout/table/': typeof LayoutTableIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/table/$tableId' | '/chart' | '/table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/table/$tableId' | '/chart' | '/table'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/table/$tableId'
    | '/_layout/chart/'
    | '/_layout/table/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/table/$tableId",
        "/_layout/chart/",
        "/_layout/table/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/table/$tableId": {
      "filePath": "_layout/table/$tableId.tsx",
      "parent": "/_layout"
    },
    "/_layout/chart/": {
      "filePath": "_layout/chart/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/table/": {
      "filePath": "_layout/table/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
